mysql: # MySQL storage
  hostname: "localhost"
  port: "3306"
  database: "test"
  username: "root"
  password: ""

elevator: # Elevator Template
  # Item name
  name: "&6&lELEVATOR"
  # Enables / Disables Glow
  glow: false
  # Item lore
  #
  # Placeholders:
  # {material} - Material name
  lore: []
  # Item enchantment (Remember in disable the glow) - (All Minecraft enchants https://ghostbin.co/paste/w2ttacs)
  enchantment: []

# Worlds that elevators are unallowed
blacklist:
  - "world"
  - "world1"

# Max distance the elevator will be teleported
maxdistance: 10

sound: # Elevator Sounds - All MineCraft Sounds - https://helpch.at/docs/1.8.8/index.html?org/bukkit/Sound.html
  up: # Sound when taken one above floor
    # Enable / Disable Sound
    use: true
    # Sound Type
    type: "ORB_PICKUP"
    # Volume of the Sound
    volume: 1.0
    # Pitch of the Sound
    pitch: 1.0
  down: # Sound when taken one bellow floor
    # Enable / Disable Sound
    use: true
    # Sound Type
    type: "ORB_PICKUP"
    # Volume of the Sound
    volume: 1.0
    # Pitch of the Sound
    pitch: 1.0
  place: # Sound when placing an elevator
    # Enable / Disable Sound
    use: true
    # Sound Type
    type: "ANVIL_LAND"
    # Volume of the Sound
    volume: 1.0
    # Pitch of the Sound
    pitch: 1.0
  break: # Sound when breaking an elevator
    # Enable / Disable Sound
    use: true
    # Sound Type
    type: "ITEM_BREAK"
    # Volume of the Sound
    volume: 1.0
    # Pitch of the Sound
    pitch: 1.0